{{- if .Values.firstInstall -}}
kind: Service
apiVersion: v1
metadata:
  name: courie-web
  labels:
    app: courie-web
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: courie-web
  type: ClusterIP
{{- end }}